# @package _global_

defaults:
  - base_env

# Env structure
env:
  _target_: protoverse.envs.path_follower.env.PathFollowing
  config:
    enable_height_termination: False
    max_episode_length: 300

    path_follower_params:
      num_traj_samples: 10
      fail_dist: 4.
      fail_height_dist: 0.5
      traj_sample_timestep: 0.5
      path_generator:
        num_verts: 101
        dtheta_max: 2.
        sharp_turn_prob: 0.02
        accel_max: 2.
        speed_max: 5.
        speed_min: 0.

        fixed_path: True # False
        slow: False # False
        use_forward_path_only: True # False

        height_conditioned: ${..height_conditioned}
        start_speed_max: 3.
        speed_z_max: 0.5
        accel_z_max: 0.2
        head_height_max: 1.5
        head_height_min: 0.4
        use_naive_path_generator: False
      path_obs_size: ${eval:${.num_path_obs_per_point}*${.num_traj_samples}}
      enable_path_termination: True
      height_conditioned: True
      num_path_obs_per_point: ${eval:${.height_conditioned}*1+2}

    foot_obs_params:
      obs_size: 42

    reward_config:
      positive_constant: 0.0
      scale_with_dt: True

      use_yaw_frame_tracking: True
      feet_air_time_mode: positive_biped
      feet_air_time_threshold: 0.4
      dof_pos_limits_scope: ankles

      target_base_height: 0.78 # g1
      target_feet_height: 0.12 # g1
      close_feet_threshold: 0.15 # g1

      reward_scales:
        path: 1.0
        
eval_overrides:
  env:
    config:
      max_episode_length: 300
      path_follower_params:
        enable_path_termination: False


