# @package _global_

defaults:
  - base_env

# Env structure
env:
  _target_: protoverse.envs.steering.env.Steering
  config:
    command_style: isaac        # "isaac" or "steering"
    obs_mode: isaac             # "isaac" or "steering"
    enable_height_termination: True
    with_foot_obs: False

    # Isaac-style commands (mirrors legged-gym)
    commands:
      curriculum: false
      max_curriculum: 1.0
      num_commands: 4
      resampling_time: 10.0     # [s]
      heading_command: true
      ranges:
        lin_vel_x: [-1.0, 1.0]
        lin_vel_y: [-1.0, 1.0]
        ang_vel_yaw: [-1.0, 1.0]
        heading: [-3.14, 3.14]


    steering_params:
      heading_change_steps_min: 40
      heading_change_steps_max: 150
      random_heading_probability: 0.2
      standard_heading_change: 1.57
      tar_speed_min: 0.0 # 1.0
      tar_speed_max: 1.414 # 2
      standard_speed_change: 0.3
      stop_probability: 0.05
      obs_size: 3

    foot_obs_params:
      obs_size: 42
      
    reward_config:
      positive_constant: 1.0 # TODO
      scale_with_dt: True

      use_yaw_frame_tracking: True
      feet_air_time_mode: positive_biped
      feet_air_time_threshold: 0.4
      dof_pos_limits_scope: all # ankles

      target_base_height: 0.78 # g1
      target_feet_height: 0.12 # g1
      close_feet_threshold: 0.15 # g1

      pn_reach_threshold: 1.0
      pn_distance_clip: False

      reward_scales:

        # ViNL
        lin_vel_z:       -2.0
        ang_vel_xy:      -0.05     
        # torque:          -0.00001
        # dof_acc:         -3.5e-8    # -3.5e-8 -2.5e-7 
        # feet_air_time:    1.0
        # collision:       -1.0
        # action_rate:     -0.01
        # slippage: -0.1 # -1.0
        dof_pos_limits: -5.0 # -10.0 

        # ASAP
        # feet_ori: -2.0
        base_height: -10.0 
        # feet_height: -2.5
        # upperbody_joint_angle_freeze: -0.2
        # feet_heading_alignment: -0.3   # check     
        # penalty_close_feet_xy: -10.
        # penalty_ang_vel_xy_torso: -1.0

        # H1RoughEnvCfg+Path
        # termination: -100.0
        # path:             8.0 
        tracking_lin_vel: 10.0 # 10.0 
        tracking_ang_vel: 0.5 # 5.0 
        # feet_air_time: 1.0             
        # slippage: -0.25                  
        # dof_pos_limits: -1.0
        # upperbody_joint_angle_freeze_hip: -0.2
        # upperbody_joint_angle_freeze_arms: -0.2
        # upperbody_joint_angle_freeze_torso: -0.1
        # orientation: -1.0
        # action_rate: -0.005
        # dof_acc: -1.25e-7

        # Parkour
        # collision: -10.0
        # tracking_lin_vel: 1.0 
        # tracking_ang_vel: 1.5
        # orientation: -2.0
        dof_vel: -1e-3 
        action_rate: -0.01
        # torques: -1.0e-5
        dof_acc: -2.5e-7
        # dof_error: -0.3
        hip_pos: -0.1
        slippage: -0.25
        # LEGO-H
        # tracking_goal_vel: 1.0
        # tracking_yaw: 0.5
        # ang_vel_xy: -1.0
        orientation: -1.0

        # dof_acc: -3.5e-8
        # collision: -10.0
        # action_rate: -0.01
        # delta_torques: -1.0e-7
        # torques: -1.0e-5
        # hip_pos: -0.5
        # dof_error: -0.04
        # feet_stumble: -1.0
        # feet_air_time: 1.0    
        # base_height: -35.0     
        # pn_distance: 1.0      
        contact:  0.18
        feet_swing_height: -20.0

# Globally accessible parameters
