# @package _global_

defaults:
  - base_env

# Env structure
env:
  _target_: protoverse.envs.steering.env.Steering
  config:
    enable_height_termination: True
    with_foot_obs: False

    steering_params:
      heading_change_steps_min: 40
      heading_change_steps_max: 150
      random_heading_probability: 0.2
      standard_heading_change: 1.57
      tar_speed_min: 1.2
      tar_speed_max: 6
      standard_speed_change: 0.3
      stop_probability: 0.05
      obs_size: 3

    foot_obs_params:
      obs_size: 42
      
    reward_config:
      positive_constant: 0.0
      scale_with_dt: True

      target_base_height: 0.78 # g1
      target_feet_height: 0.12 # g1

      reward_scales:
        path:             2.0 
        lin_vel_z:       -2.0
        ang_vel_xy:      -0.05      # -1.0
        torque:          -0.00001
        dof_acc:         -2.5e-7    # -3.5e-8
        feet_air_time:    1.0
        collision:       -1.0
        action_rate:     -0.01

        # slippage: -1.0
        # feet_ori: -2.0
        # dof_pos_limits: -10.0 
        # base_height: -10.0 # TODO ??
        # feet_height: -2.5
        # upperbody_joint_angle_freeze: -0.2
        # feet_heading_alignment: -0.3
        
        # penalty_close_feet_xy: -10.
        # penalty_ang_vel_xy_torso: -1.0
        # penalty_hip_pos: -1.0



        
# Globally accessible parameters
