# @package _global_

defaults:
  - base_env

# Env structure
env:
  _target_: protoverse.envs.steering.env_curriculum.SteeringCurriculum
  config:
    enable_height_termination: True
    with_foot_obs: False

    steering_curriculum:
      difficulty:
        diff_step_up:   0.10   # difficulty += when success streak reached
        diff_step_down: 0.10   # difficulty -= when fail/stagnate
        succ_needed:    2
        fail_needed:    2

      starts:
        flat_mix_k:     1.0    # p_flat = clamp(1 - k*d, flat_min_prob, 1)
        flat_min_prob:  0.10   # never fully remove flat starts

      heading:
        min_goal_dist_m:           1.5
        max_goal_dist_m:           8.0
        max_heading_jitter_deg:    60   # jitter amplitude at d=1
        random_heading_base:       0.10 # at d=0
        random_heading_max:        0.60 # at d=1

      success:
        # Projected progress threshold (meters) scales with difficulty:
        # need_prog(d) = lerp(min_progress_m_at_d0, min_progress_m_at_d1, d)
        min_progress_m_at_d0: 2.0
        min_progress_m_at_d1: 15.0 # TODO: func of episode_length

        # Optional: if >0, after this many non-success episodes in a row,
        # also step difficulty down once.
        stagnant_eps_need: 0   # 0 disables stagnation backoff

    steering_params:
      heading_change_steps_min: 40
      heading_change_steps_max: 150
      random_heading_probability: 0.2
      standard_heading_change: 1.57
      tar_speed_min: 1.2
      tar_speed_max: 3
      standard_speed_change: 0.3
      stop_probability: 0.05
      obs_size: 3

    foot_obs_params:
      obs_size: 42
      
    reward_config:
      positive_constant: 0.0
      scale_with_dt: True

      use_yaw_frame_tracking: True
      feet_air_time_mode: positive_biped
      feet_air_time_threshold: 0.4
      dof_pos_limits_scope: ankles

      target_base_height: 0.78 # g1
      target_feet_height: 0.12 # g1
      close_feet_threshold: 0.15 # g1

      reward_scales:

        path:             1.0 

        # ViNL
        # lin_vel_z:       -2.0
        # ang_vel_xy:      -1.0      
        # torque:          -0.00001
        # dof_acc:         -3.5e-8    # -3.5e-8 -2.5e-7 
        # feet_air_time:    1.0
        # collision:       -1.0
        # action_rate:     -0.01
        # slippage: -0.1 # -1.0
        # dof_pos_limits: -10.0 # -10.0 

        # ASAP
        # feet_ori: -2.0
        # base_height: -10.0 
        # feet_height: -2.5
        # upperbody_joint_angle_freeze: -0.2
        # feet_heading_alignment: -0.3   # check     
        # penalty_close_feet_xy: -10.
        # penalty_ang_vel_xy_torso: -1.0
        # penalty_hip_pos: -1.0. - < 

        # H1RoughEnvCfg
        # termination: -100.0
        tracking_lin_vel: 1 #10.0
        tracking_ang_vel: 2 # 5.0
        feet_air_time: 0.25 # 1.0             
        slippage: -0.25                  
        dof_pos_limits: -1.0
        upperbody_joint_angle_freeze_hip: -0.2
        upperbody_joint_angle_freeze_arms: -0.2
        upperbody_joint_angle_freeze_torso: -0.1
        orientation: -1.0
        action_rate: -0.005
        dof_acc: -1.25e-7
        # progress: 0.2

        
# Globally accessible parameters
