# @package _global_

defaults:
  - base

robot:
  body_names: ['pelvis',
               'left_hip_pitch_link', 'left_hip_roll_link', 'left_hip_yaw_link', 'left_knee_link', 'left_ankle_pitch_link', 'left_ankle_roll_link',
               'right_hip_pitch_link', 'right_hip_roll_link', 'right_hip_yaw_link', 'right_knee_link', 'right_ankle_pitch_link', 'right_ankle_roll_link',
               'torso_link',
               'left_shoulder_pitch_link', 'left_shoulder_roll_link', 'left_shoulder_yaw_link', 'left_elbow_link', 'left_wrist_roll_rubber_hand',
               'right_shoulder_pitch_link', 'right_shoulder_roll_link', 'right_shoulder_yaw_link', 'right_elbow_link', 'right_wrist_roll_rubber_hand']

  dof_names: ['left_hip_pitch_joint', 'left_hip_roll_joint', 'left_hip_yaw_joint', 'left_knee_joint', 'left_ankle_pitch_joint', 'left_ankle_roll_joint',
              'right_hip_pitch_joint', 'right_hip_roll_joint', 'right_hip_yaw_joint', 'right_knee_joint', 'right_ankle_pitch_joint', 'right_ankle_roll_joint',
              'waist_yaw_joint',
              'left_shoulder_pitch_joint', 'left_shoulder_roll_joint', 'left_shoulder_yaw_joint', 'left_elbow_joint', 'left_wrist_roll_joint',
              'right_shoulder_pitch_joint', 'right_shoulder_roll_joint', 'right_shoulder_yaw_joint', 'right_elbow_joint', 'right_wrist_roll_joint']

  trackable_bodies_subset: ['pelvis', 'torso_link', 'left_ankle_roll_link', 'right_ankle_roll_link']

  # Observation parameters
  dof_obs_size: ${eval:${len:${.dof_body_ids}}*6}
  number_of_actions: 23
  self_obs_max_coords_size: 358  # 1 + 24*(3+6+3+3) - 3  (24 bodies listed above)
  robot_obs_size: 78

  with_cam_obs: False
  with_foot_sensors: False

  # Control parameters
  dof_body_ids: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23 ]
  joint_axis: ['y','x','z','y','y','x',  'y','x','z','y','y','x',  'z',  'y','x','z','y','x',  'y','x','z','y','x']
  dof_effort_limits: [88.0, 88.0, 88.0, 139.0, 50.0, 50.0,
                      88.0, 88.0, 88.0, 139.0, 50.0, 50.0,
                      88.0,
                      25.0, 25.0, 25.0, 25.0, 25.0,
                      25.0, 25.0, 25.0, 25.0, 25.0]
  dof_vel_limits: [32.0, 32.0, 32.0, 20.0, 37.0, 37.0,
                   32.0, 32.0, 32.0, 20.0, 37.0, 37.0,
                   32.0,
                   37.0, 37.0, 37.0, 37.0, 37.0,
                   37.0, 37.0, 37.0, 37.0, 37.0]
  dof_armatures: [0.03, 0.03, 0.03, 0.03, 0.03, 0.03,
                  0.03, 0.03, 0.03, 0.03, 0.03, 0.03,
                  0.03,
                  0.03, 0.03, 0.03, 0.03, 0.03,
                  0.03, 0.03, 0.03, 0.03, 0.03]
  dof_joint_frictions: [0.03, 0.03, 0.03, 0.03, 0.03, 0.03,
                        0.03, 0.03, 0.03, 0.03, 0.03, 0.03,
                        0.03,
                        0.03, 0.03, 0.03, 0.03, 0.03,
                        0.03, 0.03, 0.03, 0.03, 0.03]

  key_bodies: ["left_ankle_roll_link", "right_ankle_roll_link"]
  non_termination_contact_bodies: ["left_ankle_pitch_link", "left_ankle_roll_link", "right_ankle_pitch_link", "right_ankle_roll_link"]

  upper_dof_names: ['left_shoulder_pitch_joint', 'left_shoulder_roll_joint', 'left_shoulder_yaw_joint', 'left_elbow_joint', 'left_wrist_roll_joint',
                    'right_shoulder_pitch_joint', 'right_shoulder_roll_joint', 'right_shoulder_yaw_joint', 'right_elbow_joint', 'right_wrist_roll_joint']

  right_foot_name: "right_ankle_roll_link"
  left_foot_name: "left_ankle_roll_link"
  head_body_name: "torso_link" 
  penalize_contacts_on: ['pelvis',
                         'left_hip_pitch_link', 'left_hip_roll_link', 'left_hip_yaw_link',
                         'right_hip_pitch_link', 'right_hip_roll_link', 'right_hip_yaw_link',
                         'left_shoulder_pitch_link', 'left_shoulder_roll_link', 'left_shoulder_yaw_link',
                         'right_shoulder_pitch_link', 'right_shoulder_roll_link', 'right_shoulder_yaw_link']

  ankle_dof_names: ['left_ankle_pitch_joint', 'left_ankle_roll_joint', 'right_ankle_pitch_joint', 'right_ankle_roll_joint']
  hip_joint_names:
    ['left_hip_yaw_joint','left_hip_roll_joint',
     'right_hip_yaw_joint','right_hip_roll_joint']
  arm_joint_names: ['left_shoulder_pitch_joint', 'left_shoulder_roll_joint', 'left_shoulder_yaw_joint', 'left_elbow_joint',
                    'right_shoulder_pitch_joint', 'right_shoulder_roll_joint', 'right_shoulder_yaw_joint', 'right_elbow_joint']
  torso_joint_names: ['waist_yaw_joint']
  undesired_contact_bodies: ['left_hip_pitch_link', 'left_hip_roll_link', 'left_hip_yaw_link',
                             'right_hip_pitch_link', 'right_hip_roll_link', 'right_hip_yaw_link']
  knee_joint_names: ['left_knee_joint', 'right_knee_joint']

  init_state:
    pos: [0.0, 0.0, 0.76]
    default_joint_angles:
      left_hip_pitch_joint: -0.1
      left_hip_roll_joint: 0.0
      left_hip_yaw_joint: 0.0
      left_knee_joint: 0.3
      left_ankle_pitch_joint: -0.2
      left_ankle_roll_joint: 0.0
      right_hip_pitch_joint: -0.1
      right_hip_roll_joint: 0.0
      right_hip_yaw_joint: 0.0
      right_knee_joint: 0.3
      right_ankle_pitch_joint: -0.2
      right_ankle_roll_joint: 0.0
      waist_yaw_joint: 0.0
      left_shoulder_pitch_joint: 0.0
      left_shoulder_roll_joint: 0.0
      left_shoulder_yaw_joint: 0.0
      left_elbow_joint: 0.0
      left_wrist_roll_joint: 0.0
      right_shoulder_pitch_joint: 0.0
      right_shoulder_roll_joint: 0.0
      right_shoulder_yaw_joint: 0.0
      right_elbow_joint: 0.0
      right_wrist_roll_joint: 0.0

  control:
    control_type: proportional
    use_biased_controller: False
    map_actions_to_pd_range: True
    stiffness:
      hip_yaw: 100
      hip_roll: 100
      hip_pitch: 100
      knee: 200
      ankle_pitch: 20
      ankle_roll: 20
      waist_yaw: 400
      shoulder_pitch: 90
      shoulder_roll: 60
      shoulder_yaw: 20
      elbow: 60
      wrist_roll: 20
    damping:
      hip_yaw: 2.5
      hip_roll: 2.5
      hip_pitch: 2.5
      knee: 5.0
      ankle_pitch: 0.2
      ankle_roll: 0.1
      waist_yaw: 5.0
      shoulder_pitch: 2.0
      shoulder_roll: 1.0
      shoulder_yaw: 0.4
      elbow: 1.0
      wrist_roll: 0.3

  asset:
    collapse_fixed_joints: True   # keep keyframe/aux frames if importer supports it
    replace_cylinder_with_capsule: True
    flip_visual_attachments: False
    armature: 0.001
    thickness: 0.01
    max_angular_velocity: 1000.
    max_linear_velocity: 1000.
    density: 0.001
    angular_damping: 0.
    linear_damping: 0.

    asset_file_name: "urdf/g1_23dof.urdf"
    usd_asset_file_name: "usd/g1/g1_23dof.usd"
    robot_type: g1_23dof
    self_collisions: False
    default_dof_drive_mode: 3

  sim:
    isaacgym:
      fps: 200
      decimation: 4
      substeps: 1
    isaaclab:
      fps: 200
      decimation: 4
    genesis:
      fps: 200
      decimation: 4
      substeps: 1

# Override motion lib default to use the adapted H1 variant
motion_lib:
  _target_: protoverse.utils.motion_lib_h1.H1_MotionLib

# Override simulation config to use the adapted H1 variant
env:
  config:
    mimic_reset_track:
      grace_period: 10
