name: docs

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      # Check out source.
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # This ensures the entire history is fetched so we can switch branches

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.12"

      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y libsuitesparse-dev
          pip install uv
          uv pip install --system -e ".[dev,examples]"
          uv pip install --system -r docs/requirements.txt

      # Build documentation.
      - name: Building documentation
        run: |
          sphinx-build docs/source docs/build -b dirhtml

      # Deploy to version-dependent subdirectory.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
