# @package _global_

agent:
  config:
    # Setup basic actor-critic structure
    model:
      config:
        actor:
          _target_: protoverse.agents.ppo.model.PPOActor
          _recursive_: False
          num_out: ${robot.number_of_actions}
          config:
            actor_logstd: -0.2231 # -2.9
            mu_model:
              _target_: protoverse.agents.common.mlp.MultiHeadedMLP
              _recursive_: False
              config:
                num_out: ${robot.number_of_actions}
                input_models:
                  self_obs:
                    _target_: protoverse.agents.common.common.Flatten
                    _recursive_: False
                    num_in: ${robot.self_obs_size}
                    num_out: ${.num_in}
                    config:
                      obs_key: self_obs
                      normalize_obs: True
                      norm_clamp_value: 5
                trunk:
                  _target_: protoverse.agents.common.mlp.MLP
                  _recursive_: False
                  num_out: ${robot.number_of_actions}
                  config:
                    layers:
                      - units: 512
                        activation: elu
                        use_layer_norm: false
                      - units: 256
                        activation: elu
                        use_layer_norm: false
                      - units: 128
                        activation: elu
                        use_layer_norm: false
        actor_optimizer:
          _target_: torch.optim.Adam
          lr: 1e-3
